<template>
    <div class="text-center">
        <div class="loadingio-spinner-spinner-jxdhf28fic8"><div class="ldio-qrstulbbdv8">
            <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
        </div></div>
    </div>
</template>

<script>
    export default {
        name: "Loader"
    }
</script>

<style scoped>
@keyframes ldio-qrstulbbdv8 {
    0% { opacity: 1 }
    100% { opacity: 0 }
}
.ldio-qrstulbbdv8 div {
    left: 120.78999999999999px;
    top: 47.544999999999995px;
    position: absolute;
    animation: ldio-qrstulbbdv8 linear 1.3513513513513513s infinite;
    background: #f87979;
    width: 15.419999999999998px;
    height: 17.99px;
    border-radius: 7.709999999999999px / 8.995px;
    transform-origin: 7.709999999999999px 80.955px;
}.ldio-qrstulbbdv8 div:nth-child(1) {
     transform: rotate(0deg);
     animation-delay: -1.2762762762762763s;
     background: #f87979;
 }.ldio-qrstulbbdv8 div:nth-child(2) {
      transform: rotate(20deg);
      animation-delay: -1.2012012012012012s;
      background: #f87979;
  }.ldio-qrstulbbdv8 div:nth-child(3) {
       transform: rotate(40deg);
       animation-delay: -1.1261261261261262s;
       background: #f87979;
   }.ldio-qrstulbbdv8 div:nth-child(4) {
        transform: rotate(60deg);
        animation-delay: -1.0510510510510511s;
        background: #f87979;
    }.ldio-qrstulbbdv8 div:nth-child(5) {
         transform: rotate(80deg);
         animation-delay: -0.975975975975976s;
         background: #f87979;
     }

.ldio-qrstulbbdv8 div:nth-child(6) {
    transform: rotate(100deg);
    animation-delay: -0.9009009009009009s;
    background: #f87979;
}

.ldio-qrstulbbdv8 div:nth-child(7) {
    transform: rotate(120deg);
    animation-delay: -0.8258258258258258s;
    background: #f87979;
}

.ldio-qrstulbbdv8 div:nth-child(8) {
    transform: rotate(140deg);
    animation-delay: -0.7507507507507507s;
    background: #f87979;
}

.ldio-qrstulbbdv8 div:nth-child(9) {
    transform: rotate(160deg);
    animation-delay: -0.6756756756756757s;
    background: #f87979;
}

.ldio-qrstulbbdv8 div:nth-child(10) {
    transform: rotate(180deg);
    animation-delay: -0.6006006006006006s;
    background: #f87979;
}

.ldio-qrstulbbdv8 div:nth-child(11) {
    transform: rotate(200deg);
    animation-delay: -0.5255255255255256s;
    background: #f87979;
}

.ldio-qrstulbbdv8 div:nth-child(12) {
    transform: rotate(220deg);
    animation-delay: -0.45045045045045046s;
    background: #f87979;
}

.ldio-qrstulbbdv8 div:nth-child(13) {
    transform: rotate(240deg);
    animation-delay: -0.37537537537537535s;
    background: #f87979;
}

.ldio-qrstulbbdv8 div:nth-child(14) {
    transform: rotate(260deg);
    animation-delay: -0.3003003003003003s;
    background: #f87979;
}

.ldio-qrstulbbdv8 div:nth-child(15) {
    transform: rotate(280deg);
    animation-delay: -0.22522522522522523s;
    background: #f87979;
}

.ldio-qrstulbbdv8 div:nth-child(16) {
    transform: rotate(300deg);
    animation-delay: -0.15015015015015015s;
    background: #f87979;
}

.ldio-qrstulbbdv8 div:nth-child(17) {
    transform: rotate(320deg);
    animation-delay: -0.07507507507507508s;
    background: #f87979;
}

.ldio-qrstulbbdv8 div:nth-child(18) {
    transform: rotate(340deg);
    animation-delay: 0s;
    background: #f87979;
}

.loadingio-spinner-spinner-jxdhf28fic8 {
    width: 257px;
    height: 257px;
    display: inline-block;
    overflow: hidden;
    background: none;
}

.ldio-qrstulbbdv8 {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
}

.ldio-qrstulbbdv8 div {
    box-sizing: content-box;
}

/* generated by https://loading.io/ */
</style>